# Generated by Django 4.1.7 on 2023-04-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("binanceapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_media", models.IntegerField()),
                (
                    "kline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="binanceapp.klines",
                    ),
                ),
            ],
        ),
    ]
