# Generated by Django 4.1.7 on 2023-04-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binanceapp", "0002_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="klines",
            name="simbolo",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
