# Generated by Django 4.1.7 on 2023-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binanceapp", "0003_klines_simbolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="klines",
            name="teste",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
