# Generated by Django 4.1.7 on 2023-07-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binanceapp", "0005_alter_klines_close_time_alter_klines_open_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="klines",
            name="close_time_utc",
            field=models.DateTimeField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
